### ISSUE TITLE
X20 and Webserver for HA

### ISSUE THREAD

**Issue by mike2nl** [hilch/br-plc-as-webserver#1]
Hi @hilch 
it is no issue its more a short story.
I'm running the B&R web server from up the first day he was introduced to the AR.
I have more types of webpages made for my Home Automation running now on X20CP1585 CPU's (4) which uses Powerlink and X2X bus. Made the pages in SVG, one in traditional way, one uses asp only, and one with my owm variable protocol. One main cpu as server for all other cpu's and i can control the whole thing from abrowser (pc, mobile, via strong firewall from outside).
It is alwayys fun todo new things. I have a small MP3 player module from DFRobot running on the seriaal interface. From that moment on i had a talking plc. Some special code to communicate with the iTEAD sonoff devices with the alternative Tasomta firmware here from github. For that i'm waorking to write new drivers and much other things. I love the webserver all all is dynamicly. Much better with the httpServer and httpClient library. Extrem dynamic web sites. amazing with one word.

So that's it. Short enough i hope.

**Comment by hilch** [comment]
Hi  mike2nl,
thanks for your comment. This is just a very simple example how to start with the B&R webserver. 
Of course there is much more you can do with it. 
Would be nice if anyone could add some more work to my 'awesome list' (https://github.com/hilch/awesome-B-R) to help other users.
